apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "voice-assistant.fullname" . }}-models
  labels:
    {{- include "voice-assistant.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
{{- if .Values.wakeSamples.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "voice-assistant.fullname" . }}-wake-samples
  labels:
    {{- include "voice-assistant.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.wakeSamples.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.wakeSamples.size }}
  {{- if .Values.wakeSamples.storageClassName }}
  storageClassName: {{ .Values.wakeSamples.storageClassName | quote }}
  {{- end }}
{{- end }}
